name: FM_Monitor

on:
  schedule:
    - cron: '*/5 * * * *' # 5분마다 실행
  workflow_dispatch: # 수동 실행 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run Monitor
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py
      - name: Commit changes # 새 글 ID를 저장하기 위한 단계
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_id.txt
          git commit -m "Update last post ID" || exit 0
          git push
