name: FM_Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run Monitor
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # 파일이 실제로 존재할 때만 git add를 실행하도록 수정
          if [ -f last_id.txt ]; then
            git add last_id.txt
            git commit -m "Update last post ID" || echo "No changes to commit"
            git push
          else
            echo "last_id.txt 파일이 생성되지 않아 업로드를 건너뜁니다."
          fi
